import React, { useEffect, useState } from 'react';
import './Card.css';
import logo2 from './images/logo2.png';
import man from './images/man.jpg';
import axios from 'axios';
import { Preview, print } from 'react-html2pdf';
import { useLocation } from 'react-router-dom'; 

export default function Card() {
    const location = useLocation(); 
    const [post, setPost] = useState([]);
    const [name, setName] = useState('');
    const [currentDate, setCurrentDate] = useState('');

    const [futureDate, setFutureDate] = useState('');



    useEffect(() => {
        if (location.state?.name) { 
            setName(location.state.name);
        }

        const interval = setInterval(() => {
            const currentDateObj = new Date();
            setCurrentDate(currentDateObj.toLocaleDateString());
      
            const futureDateObj = new Date(currentDateObj.getTime() + (30 * 24 * 60 * 60 * 1000)); // Adding 30 days
            setFutureDate(futureDateObj.toLocaleDateString());
          }, 1000);

          

        axios.get('http://localhost:3001/form')
            .then(res => setPost(res.data))
            .catch(err => console.log(err));
    }, [location]);

    return (
        <div>
            <div className="card-body">
                <Preview id={'jsx-template'} >
                    <div className="card">
                        <div className="title">
                            <img src={logo2} alt="logo" />
                            <h3>Ticket Trove</h3>
                        </div>
                        <div className="content">
                            <div className="photo">
                                <img src={man} alt="" width="120px" height="100px" />
                            </div>
                            <div className="unorder">
                                {post
                                    .filter(item => item.Name === name)
                                    .map(item => (
                                        <ul key={item.id}>
                                            <li>Name: {item.Name}</li>
                                            <li>ID: {item.id}</li>
                                            <li>Source: {item.Source}</li>
                                            <li>Destination: {item.Destination}</li>
                                            <li>Address: {item.Address}</li>
                                            <li>Valid till: {futureDate}</li>
                                        </ul>
                                    ))}
                            </div>
                        </div>
                        <div className="foot">
                            <h3>Pass Generated by Ticket Trove</h3>
                        </div>
                    </div>
                </Preview>
                
                    <button onClick={()=>print('card', 'jsx-template')} className='download-button'> print</button>
                
            </div>
        </div>
    );
}
